version: "3.4"

services:
  adminer:
      image: michalhosna/adminer
      ports:
        - 8080:8080
      environment:
        ADMINER_DB: support
        ADMINER_DRIVER: pgsql
        ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        ADMINER_SERVER: database
        ADMINER_USERNAME: admin
        ADMINER_AUTOLOGIN: 1
        ADMINER_NAME: supportWebsite


  php:
    build:
      context: .
      target: php_dev
    restart: unless-stopped
    volumes:
        - ./:/srv/app
        - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
        - php_socket:/var/run/php
    healthcheck:
          interval: 10s
          timeout: 3s
          retries: 3
          start_period: 30s
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy$$
      STABILITY: ${STABILITY:-stable}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}

  caddy:
    command: [ "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch" ]
    build:
      context: .
      target: caddy_base
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, caddy:80
    restart: unless-stopped
    volumes:  
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
 
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  database_data: