version: "3.4"

services:
  adminer:
      image: michalhosna/adminer
      ports:
        - 8081:8080
      environment:
        ADMINER_DB: support
        ADMINER_DRIVER: pgsql
        ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        ADMINER_SERVER: database
        ADMINER_USERNAME: admin
        ADMINER_AUTOLOGIN: 1
        ADMINER_NAME: supportWebsite

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  database_data: